[package]
name = "message-scheduler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.2"
rocket = "0.5.0-rc.2"
tokio = "1.21.2"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
